### ISSUE TITLE
ModifyElementController/return value

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#10]
Behaviour: ModifyElementController/return value

Annotations for the test cases:

    @TestedBehaviour("return value")
    @TestedService("ModifyElementController")

The production code is at com.kodekonveyor.repo.api.ModifyElementController.java
The testcase base should be at com.kodekonveyor.repo.api.ModifyElementControllerTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.ModifyElementControllerReturnValueTest.java

The return value of operations is the DTO received

The service:
        
        
ModifyElementController
[![ModifyElementController](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ModificationDTO
[![ModificationDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/61baa7ff-edc0-4de9-8ffa-323f21fdf0b0.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#61baa7ff-edc0-4de9-8ffa-323f21fdf0b0)
    
RepositoryEntity
[![RepositoryEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2f10971b-5a84-40d6-a979-c3319de83e6c.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2f10971b-5a84-40d6-a979-c3319de83e6c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by sushmavejamdla** [comment]
Grab

**Comment by sushmavejamdla** [comment]
grab

**Comment by magwas** [comment]
please note that the description is updated

**Comment by magwas** [comment]
ungrabbing due to inactivity
