### ISSUE TITLE
ConsistencyCheckService/constraint checking

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#12]
Behaviour: ConsistencyCheckService/constraint checking

Annotations for the test cases:

    @TestedBehaviour("constraint checking")
    @TestedService("ConsistencyCheckService")

The production code is at com.kodekonveyor.repo.init.ConsistencyCheckService.java
The testcase base should be at com.kodekonveyor.repo.init.ConsistencyCheckServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.init.ConsistencyCheckServiceConstraintCheckingTest.java

the constraints defined by a plugin is checked by a service receiving lists of deleted, newly created and modified element.
A constraint violation raises a ConstraintException.

The ConsistencyCheckService service call constraint checking services of all plugins.

It looks up all the plugins, obtains the name of its constraintCheckService, obtains the service registered by that name, and calls it with the modifications.

ModifyElementController first looks up the deleted and modified elements using LookupDeletedAndModifiedElementsService. 
If any of them missing, LookupDeletedAndModifiedElementsService throws a ConstraintException.
After, it
* creates a new tag with a random name starting with "_stage_".
* creates the elements as described in the element modifications behaviour
* calls ConsistencyCheckService with the modification
* deletes the stage tag

The service:
        
        
ConsistencyCheckService
[![ConsistencyCheckService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4218c582-8327-49bf-8707-a89f5ac33234.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4218c582-8327-49bf-8707-a89f5ac33234)
    
DTOs and Entities:
        
ModificationDTO
[![ModificationDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/61baa7ff-edc0-4de9-8ffa-323f21fdf0b0.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#61baa7ff-edc0-4de9-8ffa-323f21fdf0b0)
    
RepositoryEntity
[![RepositoryEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2f10971b-5a84-40d6-a979-c3319de83e6c.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2f10971b-5a84-40d6-a979-c3319de83e6c)
    
PluginEntity
[![PluginEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2b05b2ba-6237-4565-9bf4-fff3ee892519.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2b05b2ba-6237-4565-9bf4-fff3ee892519)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by mahesh9932** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity
