### ISSUE TITLE
MetamodelCheckService/metamodel checking

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#13]
Behaviour: MetamodelCheckService/metamodel checking

Annotations for the test cases:

    @TestedBehaviour("metamodel checking")
    @TestedService("MetamodelCheckService")

The production code is at com.kodekonveyor.repo.init.MetamodelCheckService.java
The testcase base should be at com.kodekonveyor.repo.init.MetamodelCheckServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.init.MetamodelCheckServiceMetamodelCheckingTest.java

metamodel checking receives no parameters

it checks whether the metamodel elements are there and their fields are correct

any problems with the metamodel elements are corrected

the metamodel elements belong to initial_commit

the metamodel checking logic of all plugins are run from MetamodelCheckService

it looks up all the PluginEntities, gets the metamodel check services by name and run them

The service:
        
        
MetamodelCheckService
[![MetamodelCheckService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/ef4b5bf1-714f-4732-aa79-07de2d781ce1.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#ef4b5bf1-714f-4732-aa79-07de2d781ce1)
    
DTOs and Entities:
        
PluginEntity
[![PluginEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2b05b2ba-6237-4565-9bf4-fff3ee892519.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2b05b2ba-6237-4565-9bf4-fff3ee892519)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by mahesh9932** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity

**Comment by mahesh9932** [comment]
It is already completed why it is ungrabbed
