### ISSUE TITLE
GetServiceByNameService/obtain bean

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#15]
Behaviour: GetServiceByNameService/obtain bean

Annotations for the test cases:

    @TestedBehaviour("obtain bean")
    @TestedService("GetServiceByNameService")

The production code is at com.kodekonveyor.repo.api.GetServiceByNameService.java
The testcase base should be at com.kodekonveyor.repo.api.GetServiceByNameServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.GetServiceByNameServiceObtainBeanTest.java

returns a managed bean using WebAppInitializer.context.getBean(name)

The service:
	
	
GetServiceByNameService
[![GetServiceByNameService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/95f0a90d-0442-4642-9ef7-21b89bd7ebea.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#95f0a90d-0442-4642-9ef7-21b89bd7ebea)
    
DTOs and Entities:
	

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by akkishah1993** [comment]
Grab
