### ISSUE TITLE
CreateElementService/element creation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#19]
Behaviour: CreateElementService/element creation

Annotations for the test cases:

    @TestedBehaviour("element creation")
    @TestedService("CreateElementService")

The production code is at com.kodekonveyor.repo.api.CreateElementService.java
The testcase base should be at com.kodekonveyor.repo.api.CreateElementServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.CreateElementServiceElementCreationTest.java

The element is created with all its fields, in the repository given.

The service:
        
        
CreateElementService
[![CreateElementService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/10b9896a-b9c1-4883-8d35-64f1546a9fab.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#10b9896a-b9c1-4883-8d35-64f1546a9fab)
    
DTOs and Entities:
        
ElementDTO
[![ElementDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/d5dcac41-6ab7-4be6-8e55-4ece578c7037.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#d5dcac41-6ab7-4be6-8e55-4ece578c7037)
    
RepositoryEntity
[![RepositoryEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2f10971b-5a84-40d6-a979-c3319de83e6c.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2f10971b-5a84-40d6-a979-c3319de83e6c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
No entity access has been modeled
