### ISSUE TITLE
LookupElementService/element lookup

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#20]
Behaviour: LookupElementService/element lookup

Annotations for the test cases:

    @TestedBehaviour("element lookup")
    @TestedService("LookupElementService")

The production code is at com.kodekonveyor.repo.api.LookupElementService.java
The testcase base should be at com.kodekonveyor.repo.api.LookupElementServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.LookupElementServiceElementLookupTest.java

Elements can be looked up based on the id and tag of the element. The tag refers to the repository.
Elements are looked up in the commit referred to by the tag. If not found, and the previous commit is in the same repository, the previous commit is looked up recursively.
If the element is not found, a null is returned.

The service:
        
        
LookupElementService
[![LookupElementService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/89478db9-c854-464e-87b6-6a74f33b31d6.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#89478db9-c854-464e-87b6-6a74f33b31d6)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ElementDTO
[![ElementDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/d5dcac41-6ab7-4be6-8e55-4ece578c7037.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#d5dcac41-6ab7-4be6-8e55-4ece578c7037)
    
RepositoryEntity
[![RepositoryEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2f10971b-5a84-40d6-a979-c3319de83e6c.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2f10971b-5a84-40d6-a979-c3319de83e6c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
No entity access has been modeled.
