### ISSUE TITLE
CheckCoreMetamodelService/core meta check

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#24]
Behaviour: CheckCoreMetamodelService/core meta check

Annotations for the test cases:

    @TestedBehaviour("core meta check")
    @TestedService("CheckCoreMetamodelService")

The production code is at com.kodekonveyor.repo.plugins.core.CheckCoreMetamodelService.java
The testcase base should be at com.kodekonveyor.repo.plugins.core.CheckCoreMetamodelServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.plugins.core.CheckCoreMetamodelServiceCoreMetaCheckTest.java

The stored data is checked to make sure that the core metamodel exists and adheres to the rules.

If there is any problem, the data is fixed.

the metamodel elements belong to initial_commit

The service:
        
        
CheckCoreMetamodelService
[![CheckCoreMetamodelService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/74ce617e-ab1c-4067-98fa-916b49fd2254.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#74ce617e-ab1c-4067-98fa-916b49fd2254)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
Missing parameters in the model.
