### ISSUE TITLE
CheckReferenceService/element validation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#26]
Behaviour: CheckReferenceService/element validation

Annotations for the test cases:

    @TestedBehaviour("element validation")
    @TestedService("CheckReferenceService")

The production code is at com.kodekonveyor.repo.api.CheckReferenceService.java
The testcase base should be at com.kodekonveyor.repo.api.CheckReferenceServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.CheckReferenceServiceElementValidationTest.java

Reference fields must point to existing elements which will be available after the operation in the repository, or in an external repository.
Elements should either be a memento, or fully defined.

It is an error to have more than one commit in the modification

the commit of the created elements (except tags) is the current commit. if there is no commit in the modification, one is created with a random name/id

if any of the elements does not have a commit associated, the necessary relationship is created

the commit of all of the elements are fixed in the DTO if needed before passed on to CreateElementService

any elements created and not in the modification are added to the modification

References are checked by CheckReferenceService

Local references and remote references using a repository available in the server are checked for the existence of the element referred to.
Other remote references are checked for syntax.

CheckReferenceService returns
* SYNTAX if the reference is syntactically invalid
* FOUND_LOCAL if the reference is local and found
* NOT_FOUND_LOCAL if the reference is local and not found
* FOUND_SERVER if the remote repository is in the server and the element is found
* NOT_FOUND_SERVER if the remote repository is in the server and the element is not found
* REMOTE if the reference points to a repository not in the server and is syntactically correct

ModifyElementController accepts FOUND_LOCAL, FOUND_SERVER, and REMOTE references.
See the "data model" objective for details.

The service:
        
        
CheckReferenceService
[![CheckReferenceService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2855e9d6-a087-4194-a5f2-12e6c9b91667.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2855e9d6-a087-4194-a5f2-12e6c9b91667)
    
DTOs and Entities:
        

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
There are missing parts in the model. Which entity should it access? I guess it should call multiple services as well, since it has many responsibilities

- Syntax check
- Check if remote
- Check if local with remote syntax
- Check if existing locally
