### ISSUE TITLE
CheckCoreConsistencyService/no loops

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#27]
Behaviour: CheckCoreConsistencyService/no loops

Annotations for the test cases:

    @TestedBehaviour("no loops")
    @TestedService("CheckCoreConsistencyService")

The production code is at com.kodekonveyor.repo.plugins.core.CheckCoreConsistencyService.java
The testcase base should be at com.kodekonveyor.repo.plugins.core.CheckCoreConsistencyServiceTestBase.java
The testcase should probably be at com.kodekonveyor.repo.plugins.core.CheckCoreConsistencyServiceNoLoopsTest.java

The rules in the core elements objective are checked.

The service:
        
        
CheckCoreConsistencyService
[![CheckCoreConsistencyService](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/83fea269-bbb1-4947-8282-523c7a279d11.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#83fea269-bbb1-4947-8282-523c7a279d11)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ModificationDTO
[![ModificationDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/61baa7ff-edc0-4de9-8ffa-323f21fdf0b0.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#61baa7ff-edc0-4de9-8ffa-323f21fdf0b0)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by gplkrnkr** [comment]
grab

**Comment by magwas** [comment]
ungrabbed due to inactivity. Please regrab if you want to continue.
