### ISSUE TITLE
ModifyElementController/constraint checking

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#3]
Behaviour: ModifyElementController/constraint checking

Annotations for the test cases:

    @TestedBehaviour("constraint checking")
    @TestedService("ModifyElementController")

The production code is at com.kodekonveyor.repo.api.ModifyElementController.java
The testcase base should be at com.kodekonveyor.repo.api.ModifyElementControllerTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.ModifyElementControllerConstraintCheckingTest.java

the constraints defined by a plugin is checked by a service receiving lists of deleted, newly created and modified element.
A constraint violation raises a ConstraintException.

The ConsistencyCheckService service call constraint checking services of all plugins.

It looks up all the plugins, obtains the name of its constraintCheckService, obtains the service registered by that name, and calls it with the modifications.

The service:
        
        
ModifyElementController
[![ModifyElementController](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ModificationDTO
[![ModificationDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/61baa7ff-edc0-4de9-8ffa-323f21fdf0b0.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#61baa7ff-edc0-4de9-8ffa-323f21fdf0b0)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
* It's not clear what to do here.
* How a constraint should look like?
* Where does constraints come from?
* repoName should be in relation with String
* Why do we identify repo by name instead of id?
* I think DB operation is missing here.
* I'm happy about UUID id-s. Centralized id management is not needed any more :)

**Comment by nitinpawar1999** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity
