### ISSUE TITLE
ModifyElementController/element validation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#6]
Behaviour: ModifyElementController/element validation

Annotations for the test cases:

    @TestedBehaviour("element validation")
    @TestedService("ModifyElementController")

The production code is at com.kodekonveyor.repo.api.ModifyElementController.java
The testcase base should be at com.kodekonveyor.repo.api.ModifyElementControllerTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.ModifyElementControllerElementValidationTest.java

Reference fields must point to existing elements which will be available after the operation in the repository, or in an external repository.
Elements should either be a memento, or fully defined.

It is an error to have more than one commit in the modification

the commit of the created elements (except tags) is the current commit. if there is no commit in the modification, one is created with a random name/id

if any of the elements does not have a commit associated, the necessary relationship is created

the commit of all of the elements are fixed in the DTO if needed before passed on to CreateElementService

any elements created and not in the modification are added to the modification

References are checked by CheckReferenceService

Local references and remote references using a repository available in the server are checked for the existence of the element referred to.
Other remote references are checked for syntax.

CheckReferenceService returns
* SYNTAX if the reference is syntactically invalid
* FOUND_LOCAL if the reference is local and found
* NOT_FOUND_LOCAL if the reference is local and not found
* FOUND_SERVER if the remote repository is in the server and the element is found
* NOT_FOUND_SERVER if the remote repository is in the server and the element is not found
* REMOTE if the reference points to a repository not in the server and is syntactically correct

ModifyElementController accepts FOUND_LOCAL, FOUND_SERVER, and REMOTE references.
See the "data model" objective for details.

The service:
        
        
ModifyElementController
[![ModifyElementController](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#0f1f6f50-04b4-4a94-88cb-c41ac1a9fe6e)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ModificationDTO
[![ModificationDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/61baa7ff-edc0-4de9-8ffa-323f21fdf0b0.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#61baa7ff-edc0-4de9-8ffa-323f21fdf0b0)
    
RepositoryEntity
[![RepositoryEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/2f10971b-5a84-40d6-a979-c3319de83e6c.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#2f10971b-5a84-40d6-a979-c3319de83e6c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
* why do we need ElementModificationDTO? We can identify the element by ID and know the previous state from DB if it's important.
* DB call is missing

**Comment by mayankus** [comment]
grab

**Comment by szirbucz** [comment]
It's a big task currently, and not in the level of an average coder. We should model it more in detail by adding a ReferenceValidationService, and one task should be collecting all the references from the DTO and other is to validate them via this service.

**Comment by mayankus** [comment]
grab

**Comment by magwas** [comment]
I should check the reason of the model build failure.

**Comment by magwas** [comment]
ungrabbed due to inactivity
