### ISSUE TITLE
ReadElementController/Element presentation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/repo-server#9]
Behaviour: ReadElementController/Element presentation

Annotations for the test cases:

    @TestedBehaviour("Element presentation")
    @TestedService("ReadElementController")

The production code is at com.kodekonveyor.repo.api.ReadElementController.java
The testcase base should be at com.kodekonveyor.repo.api.ReadElementControllerTestBase.java
The testcase should probably be at com.kodekonveyor.repo.api.ReadElementControllerElementPresentationTest.java

The representation contains all of the fields of the element, plus:
* a field called sourceIn, listing all the relations where the element is source and the target is either in the repository and accessible for the user, or in an external repository
* a field called targetIn, listing all the relations where the element is target and the source is either in the repository and accessible for the user, or in an external repository

relations listed in sourceIn and targetIn does not get their relations listed

The references always contain the value of the id and commit field and no base url for locally stored elements, and whatever is defined for other elements.

See the Obtaining an element objective for external representation of id and commit.

The service:
        
        
ReadElementController
[![ReadElementController](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/d8022c7f-446b-41e9-b6b9-586c3a4de9c7.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#d8022c7f-446b-41e9-b6b9-586c3a4de9c7)
    
DTOs and Entities:
        
ElementEntity
[![ElementEntity](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/4322da00-77ce-4134-b904-9c39c4d50d06.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#4322da00-77ce-4134-b904-9c39c4d50d06)
    
ElementWithRelationsDTO
[![ElementWithRelationsDTO](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/pics/ef9252f3-dadb-4f33-a618-482fcb85747d.png)](https://repository.kodekonveyor.com/repo-server/kode-konveyor/develop/index.html#ef9252f3-dadb-4f33-a618-482fcb85747d)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by akash11235** [comment]
grab

**Comment by szirbucz** [comment]
* read operation is missing from the access relation between the controller and the entity

**Comment by magwas** [comment]
ungrabbing due to inactivity
